name: usansred
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - versioningit
  - mantid=6.8.0
  - scipy
  - pandas
  - matplotlib
  # Development dependencies
  - pre-commit
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  - pytest
  - pytest-cov
  - pytest-xdist
