name: usansred
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - versioningit
  - mantid=6.8.0
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
    - git+https://github.com/peterfpeterson/finddata@v0.8.4
  # Development dependencies
  - libmamba
  - libarchive
  - setuptools
  - pre-commit
  - anaconda-client
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  - pytest
  - pytest-cov
  - pytest-xdist
