name: usansred
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - versioningit
  - mantidworkbench=6.9.1
  - pandas
  - xlsxwriter
  - neutrons::finddata=0.10
  - pip
  # Development dependencies
  - libmamba
  - libarchive
  - setuptools
  - pre-commit
  - anaconda-client
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  - pytest
  - pytest-cov
  - pytest-xdist
  - sphinx
  - sphinx-rtd-theme
