name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          environment-file: environment.yml
          cache-environment-key: ${{ runner.os }}-env-${{ hashFiles('**/environment.yml') }}
          cache-downloads-key: ${{ runner.os }}-downloads-${{ hashFiles('**/environment.yml') }}
      - name: install additional dependencies
        run: |
          echo "installing additional dependencies if cannot be installed from conda"
      - name: run unit tests
        run: |
          echo "running unit tests"
          python -m pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
